/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsersRouteImport } from './routes/users'
import { Route as TeamsRouteImport } from './routes/teams'
import { Route as TasksRouteImport } from './routes/tasks'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as RoadmapRouteImport } from './routes/roadmap'
import { Route as RisksRouteImport } from './routes/risks'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PermissoesRouteImport } from './routes/permissoes'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LaunchesRouteImport } from './routes/launches'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as LaunchesIndexRouteImport } from './routes/launches.index'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as LaunchesIdRouteImport } from './routes/launches.$id'

const UsersRoute = UsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsRoute = TeamsRouteImport.update({
  id: '/teams',
  path: '/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const RoadmapRoute = RoadmapRouteImport.update({
  id: '/roadmap',
  path: '/roadmap',
  getParentRoute: () => rootRouteImport,
} as any)
const RisksRoute = RisksRouteImport.update({
  id: '/risks',
  path: '/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PermissoesRoute = PermissoesRouteImport.update({
  id: '/permissoes',
  path: '/permissoes',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesRoute = LaunchesRouteImport.update({
  id: '/launches',
  path: '/launches',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesIndexRoute = LaunchesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LaunchesRoute,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LaunchesIdRoute = LaunchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => LaunchesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/permissoes': typeof PermissoesRoute
  '/profile': typeof ProfileRoute
  '/risks': typeof RisksRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/launches/$id': typeof LaunchesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/launches/': typeof LaunchesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/permissoes': typeof PermissoesRoute
  '/profile': typeof ProfileRoute
  '/risks': typeof RisksRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/launches/$id': typeof LaunchesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/launches': typeof LaunchesIndexRoute
  '/products': typeof ProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/launches': typeof LaunchesRouteWithChildren
  '/login': typeof LoginRoute
  '/marketing': typeof MarketingRoute
  '/permissoes': typeof PermissoesRoute
  '/profile': typeof ProfileRoute
  '/risks': typeof RisksRoute
  '/roadmap': typeof RoadmapRoute
  '/settings': typeof SettingsRoute
  '/tasks': typeof TasksRoute
  '/teams': typeof TeamsRoute
  '/users': typeof UsersRoute
  '/launches/$id': typeof LaunchesIdRoute
  '/products/$id': typeof ProductsIdRoute
  '/launches/': typeof LaunchesIndexRoute
  '/products/': typeof ProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/launches'
    | '/login'
    | '/marketing'
    | '/permissoes'
    | '/profile'
    | '/risks'
    | '/roadmap'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/users'
    | '/launches/$id'
    | '/products/$id'
    | '/launches/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/marketing'
    | '/permissoes'
    | '/profile'
    | '/risks'
    | '/roadmap'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/users'
    | '/launches/$id'
    | '/products/$id'
    | '/launches'
    | '/products'
  id:
    | '__root__'
    | '/'
    | '/launches'
    | '/login'
    | '/marketing'
    | '/permissoes'
    | '/profile'
    | '/risks'
    | '/roadmap'
    | '/settings'
    | '/tasks'
    | '/teams'
    | '/users'
    | '/launches/$id'
    | '/products/$id'
    | '/launches/'
    | '/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LaunchesRoute: typeof LaunchesRouteWithChildren
  LoginRoute: typeof LoginRoute
  MarketingRoute: typeof MarketingRoute
  PermissoesRoute: typeof PermissoesRoute
  ProfileRoute: typeof ProfileRoute
  RisksRoute: typeof RisksRoute
  RoadmapRoute: typeof RoadmapRoute
  SettingsRoute: typeof SettingsRoute
  TasksRoute: typeof TasksRoute
  TeamsRoute: typeof TeamsRoute
  UsersRoute: typeof UsersRoute
  ProductsIdRoute: typeof ProductsIdRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams': {
      id: '/teams'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/roadmap': {
      id: '/roadmap'
      path: '/roadmap'
      fullPath: '/roadmap'
      preLoaderRoute: typeof RoadmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/risks': {
      id: '/risks'
      path: '/risks'
      fullPath: '/risks'
      preLoaderRoute: typeof RisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/permissoes': {
      id: '/permissoes'
      path: '/permissoes'
      fullPath: '/permissoes'
      preLoaderRoute: typeof PermissoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches': {
      id: '/launches'
      path: '/launches'
      fullPath: '/launches'
      preLoaderRoute: typeof LaunchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches/': {
      id: '/launches/'
      path: '/'
      fullPath: '/launches/'
      preLoaderRoute: typeof LaunchesIndexRouteImport
      parentRoute: typeof LaunchesRoute
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/launches/$id': {
      id: '/launches/$id'
      path: '/$id'
      fullPath: '/launches/$id'
      preLoaderRoute: typeof LaunchesIdRouteImport
      parentRoute: typeof LaunchesRoute
    }
  }
}

interface LaunchesRouteChildren {
  LaunchesIdRoute: typeof LaunchesIdRoute
  LaunchesIndexRoute: typeof LaunchesIndexRoute
}

const LaunchesRouteChildren: LaunchesRouteChildren = {
  LaunchesIdRoute: LaunchesIdRoute,
  LaunchesIndexRoute: LaunchesIndexRoute,
}

const LaunchesRouteWithChildren = LaunchesRoute._addFileChildren(
  LaunchesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LaunchesRoute: LaunchesRouteWithChildren,
  LoginRoute: LoginRoute,
  MarketingRoute: MarketingRoute,
  PermissoesRoute: PermissoesRoute,
  ProfileRoute: ProfileRoute,
  RisksRoute: RisksRoute,
  RoadmapRoute: RoadmapRoute,
  SettingsRoute: SettingsRoute,
  TasksRoute: TasksRoute,
  TeamsRoute: TeamsRoute,
  UsersRoute: UsersRoute,
  ProductsIdRoute: ProductsIdRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
